red_days:
    "2025":
        "01-01": "New Year's Day"
        "01-06": "Epiphany"
        "04-18": "Good Friday"
        "04-20": "Easter Sunday"
        "04-21": "Easter Monday"
        "05-01": "May Day"
        "05-29": "Ascension Day"
        "06-06": "National Day"
        "06-21": "Midsummer Day"
        "11-01": "All Saints' Day"
        "12-25": "Christmas Day"
        "12-26": "Boxing Day"
        "12-31": "New Year's Eve"

    "2026":
        "01-01": "New Year's Day"
        "01-06": "Epiphany"
        "04-03": "Good Friday"
        "04-05": "Easter Sunday"
        "04-06": "Easter Monday"
        "05-01": "May Day"
        "05-14": "Ascension Day"
        "06-06": "National Day"
        "06-20": "Midsummer Day"
        "10-31": "All Saints' Day"
        "12-25": "Christmas Day"
        "12-26": "Boxing Day"
        "12-31": "New Year's Eve"

    "2027":
        "01-01": "New Year's Day"
        "01-06": "Epiphany"
        "03-26": "Good Friday"
        "03-28": "Easter Sunday"
        "03-29": "Easter Monday"
        "05-01": "May Day"
        "05-06": "Ascension Day"
        "06-06": "National Day"
        "06-26": "Midsummer Day"
        "11-06": "All Saints' Day"
        "12-25": "Christmas Day"
        "12-26": "Boxing Day"
        "12-31": "New Year's Eve"